# Sample workflow for building and deploying a Next.js site to GitHub Pages
#
# To get started with Next.js see: https://nextjs.org/docs/getting-started
#
name: Publish

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Setup git user
        run: |
          git config --global user.name "githubBot"
          git config --global user.email "githubbot@mail.com"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: yarn
      - name: Install dependencies
        run: yarn install
      - name: Bootstrap
        run: yarn bootstrap
      - name: Publish packages
        run: yarn publish:all
      - name: Push new versions
        run: git push
