# Sample workflow for building and deploying a Next.js site to GitHub Pages
#
# To get started with Next.js see: https://nextjs.org/docs/getting-started
#
name: Publish

on:
  pull_request_target:
    types:
      - closed
    branches:
      - main

jobs:
  publish:
    if: |
      github.event.pull_request.merged == true &&
      github.event.pull_request.user.login == 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Setup git user
        run: |
          git config --global user.name "githubBot"
          git config --global user.email "githubbot@mail.com"
      - uses: actions/setup-node@v3
        with:
          registry-url: 'https://registry.npmjs.org'
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: yarn
      - name: Install dependencies
        run: yarn install
      - name: Bootstrap
        run: yarn bootstrap
      - name: Publish packages
        run: yarn publish:all
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Registry login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login --username ${{ github.actor }} --password-stdin ghcr.io
      - name: Build and push images
        run: yarn publish:images
